name: Byg et Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Kør .NET tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0' 

      - name: Gendan afhængigheder
        run: dotnet restore Test-GO-Catalog/Test-GO-Catalog.csproj

      - name: Build testprojekt
        run: dotnet build Test-GO-Catalog/Test-GO-Catalog.csproj --no-restore --configuration Release

      - name: Kør tests
        run: dotnet test Test-GO-Catalog/Test-GO-Catalog.csproj --no-build --configuration Release --logger "trx"

  build_and_push:
    name: Build og push Docker image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      IMAGE_NAME: go-catalogservice
    steps:
      - uses: actions/checkout@v4

      - name: Set dynamic image version
        id: vars
        run: echo "IMAGE_VERSION=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . -f GO-CatalogService/Dockerfile \
          -t ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION} \
          -t ${DOCKER_USER}/${IMAGE_NAME}:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
          docker push ${DOCKER_USER}/${IMAGE_NAME}:latest
